# ░█▀█░█▀▀░█▀█░█░█░▀█▀░█▀▄░█▀▀░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░
# ░█░█░█▀▀░█░█░▀▄▀░░█░░█░█░█▀▀░░░█░░░█░█░█░█░█▀▀░░█░░█░█░
# ░▀░▀░▀▀▀░▀▀▀░░▀░░▀▀▀░▀▀░░▀▀▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░

frame = "transparent"

[font]
normal = ["CartographCF Nerd Font"]
size = 12
